### ISSUE TITLE
no space left on disk

### ISSUE THREAD

**Issue by morgajel** [torchbox/vagrant-wagtail-base#16]
I'm not sure how critical this is, but when building this, I get the following error. I don't know if this means it's non-functional or if it's a benign error- this is my first look into wagtail.

==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
==> default: Zeroing free space to improve compression...
==> default: dd: 
==> default: error writing ‘/EMPTY’
==> default: : No space left on device
==> default: 38772+0 records in
==> default: 38771+0 records out
==> default: 40655273984 bytes (41 GB) copied
==> default: , 51.0281 s, 797 MB/s
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Exporting VM...
==> default: Compressing package to: /home/jmorgan/Projects/wagtail/wagtail-base-v1.2.0.box

**Comment by gasman** [comment]
This behaviour is expected. We reduce the size of the (compressed) Vagrant image by writing a file consisting of all zeros that fills the unused disk space - the "No space left on device" error appears when this process is complete (and the file is then deleted).

**Comment by morgajel** [comment]
you may want to consider echoing out something saying  "Don't worry, 'No space left' on device is expected."

When my first exposure to a technology includes big red errors and apparent incomplete processes (however intentional they may be), it makes me unfairly question the quality of the app.

**Comment by gasman** [comment]
Fair enough - that's a simple enough addition. (Actually, we could probably just redirect the error to /dev/null, so it doesn't appear at all...)

I'm a bit puzzled about how you've ended up here as your first experience of Wagtail, though - none of the main Wagtail documentation points to this repo, as far as I can see, and the readme here points you to the image on Vagrant Cloud rather than building your own copy. If you've ended up here as a new user, then your user experience has already gone pretty badly astray - perhaps there's some old documentation that we need to update...?

**Comment by morgajel** [comment]
It's the first link when you google "wagtail vagrant" :)
